---
name: Docker Image CI

on:
  pull_request:
  workflow_dispatch:


jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker-compose -f docker-compose.yml build
      - name: Test the docker image using tag:intel
        run: docker-compose -f docker-compose.yml run test-intel
      - name: Test the docker image using tag:nvidia
        run: docker-compose -f docker-compose.yml run test-nvidia
